#Creating a token for our argocd service acount
apiVersion: v1 
kind: Secret
metadata:
  name:  sa-secret
  namespace: argocd 
  annotations:
    kubernetes.io/service-account.name:  argocd-sa
    
type: kubernetes.io/service-account-token

