# apiVersion: v1
# kind: Service
# metadata:
#   name: rancher
#   namespace: cattle-system
# spec:
#   selector:
#     app: rancher
#   ports:
#   - protocol: TCP
#     port: 8080
#     targetPort: 8080
#   type: ClusterIP 




# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: rancher-expose
#   namespace: cattle-system
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: acb8d0f2e478547e0a0b5e14c4b4f72c-1734230420.us-east-1.elb.amazonaws.com      #  load balancer url 
#     http:
#       paths:
#       - path: /rancher
#         pathType: Prefix
#         backend:
#           service:
#             name: rancher
#             port:
#               number: 80



apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-ingress
  namespace: cattle-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: acb8d0f2e478547e0a0b5e14c4b4f72c-1734230420.us-east-1.elb.amazonaws.com
    http:
      paths:
      - path: /rancher
        pathType: Prefix
        backend:
          service:
            name: rancher
            port:
              number: 80
