apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: frontendapp-destination
  namespace: default
spec:
  host: frontend-service.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2