# apiVersion: networking.istio.io/v1
# kind: VirtualService
# metadata:
#   name: frontendapp-virtual-service
#   namespace: default
# spec:
#   hosts:
#   - "*"
#   gateways:
#   - frontend-gateway
#   http:
#   - name: frontendapp-split
#     route:
#     - destination:
#         host: frontend-service
#         subset: v1
#       weight: 80
#     - destination:
#         host: frontend-service
#         subset: v2
#       weight: 20
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: frontendapp-virtual-service
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/frontend-gateway  
  http:
  - name: frontendapp-route
    route:
    - destination:
        host: frontend-service        
        port:
          number: 80
