apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-app-${region}
  namespace: default
spec:
  project: boutique-project-${region}
  source:
    path: k8s/base1
    repoURL: https://github.com/kennethchinedu/NovaOps-Platform-Project
    targetRevision: main  
  
  directory:
    recurse: true
    exclude: service_account.yaml #not creating service account for the application
    

  # Sync policy
  syncPolicy:
    automated: 
      enabled: true 
      prune: true 
      selfHeal: true 
      
    syncOptions:    
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration
    - ApplyOutOfSyncOnly=true 
    - SkipDryRunOnMissingResource=true # Allow skip dry run on missing resource
